name = "Tony"
license = "GPL-3.0"
licenselink = "https://github.com/ThemeTony/hugo-theme-tony/blob/master/LICENSE"
description = "An Elegant Hugo Theme Based on WordPress Theme Tony"
homepage = "https://htony.js.org"
tags = ["simple", "Elegant", "transportation", "porting"]
features = ["medium-zoom", "social icon", "thumbnail", "Valine"]
min_version = "0.59.1"

# If the theme has a single author
[author]
    name = "Ray"
    homepage = "https://www.raycoder.me"

# If porting an existing theme
[original]
    author = "TonyHe"
    homepage = "https://www.ouorz.com"
    repo = "https://github.com/ThemeTony/tony_wordpress/"