name = "Tony"
license = "GPL-3.0"
licenselink = "https://github.com/ThemeTony/hugo-theme-tony/blob/master/LICENSE"
description = "An Elegant Hugo Theme Based on WordPress Theme Tony"
homepage = "https://htony.js.org"
tags = ["simple", "Elegant", "transportation", "porting"]
features = ["medium-zoom", "social icon", "thumbnail", "Valine","highlight.js","Google Analytics","Archives Page"]
min_version = "0.59.1"

# If the theme has a single author
[author]
    name = "Ray (so1ve)"
    homepage = "https://github.com/so1ve"

# If porting an existing theme
[original]
    author = "HelipengTony"
    homepage = "https://www.ouorz.com"
    repo = "https://github.com/HelipengTony/antony/"
